using Explore.Application.DTOs.Category;
using Explore.Application.DTOs.CustomPropertyDefinition;
using Explore.Application.DTOs.EventCustomProperty;
using Explore.Application.DTOs.EventSessionCustomProperty;
using Explore.Application.DTOs.EventSessionTemplate;
using Explore.Application.DTOs.EventTemplate;
using Explore.Domain;
using Riok.Mapperly.Abstractions;

namespace Explore.Application.Mappings;

// Response projections only. Handlers own validated writes and repositories own relationships.
[Mapper(RequiredMappingStrategy = RequiredMappingStrategy.Both)]
public static partial class CustomPropertyMapper
{
    [MapperIgnoreSource(nameof(Category.Tenant))]
    [MapProperty(nameof(Category.Parent), nameof(CategoryDto.ParentFullName), Use = nameof(ParentName))]
    public static partial CategoryDto ToDetail(Category source);

    [MapperIgnoreSource(nameof(Category.TenantId))]
    [MapperIgnoreSource(nameof(Category.Tenant))]
    [MapProperty(nameof(Category.Parent), nameof(CategoryListDto.ParentFullName), Use = nameof(ParentName))]
    public static partial CategoryListDto ToListItem(Category source);

    private static string? ParentName(Category? parent) => parent?.FullName;

    // Definition details disclose configured defaults, not tenant/answer/audit navigation graphs.
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.Tenant))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.DefaultOption))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.Values))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.CreatedAt))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.CreatedBy))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.UpdatedAt))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.UpdatedBy))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.IsDeleted))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.DeletedAt))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.DeletedBy))]
    public static partial CustomPropertyDefinitionDto ToDetail(CustomPropertyDefinition source);

    [MapperIgnoreSource(nameof(CustomPropertyDefinition.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.TenantId))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.Tenant))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.Description))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.DefaultTextValue))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.DefaultNumberValue))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.DefaultBooleanValue))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.DefaultDateTimeValue))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.DefaultOptionId))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.DefaultOption))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.MinLength))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.MaxLength))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.RegexPattern))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.MinNumber))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.MaxNumber))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.MinDateTime))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.MaxDateTime))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.AllowedUrlSchemes))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.Values))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.CreatedAt))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.CreatedBy))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.UpdatedAt))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.UpdatedBy))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.IsDeleted))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.DeletedAt))]
    [MapperIgnoreSource(nameof(CustomPropertyDefinition.DeletedBy))]
    [MapProperty("Options.Count", nameof(CustomPropertyDefinitionListDto.OptionCount))]
    public static partial CustomPropertyDefinitionListDto ToListItem(CustomPropertyDefinition source);

    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.Event))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.Tenant))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.DefaultOption))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.SourceTemplate))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.Values))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.CreatedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.CreatedBy))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.IsDeleted))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.DeletedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.DeletedBy))]
    public static partial EventCustomPropertyDefinitionDto ToDetail(EventCustomPropertyDefinition source);

    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.Event))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.TenantId))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.Tenant))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.Description))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.IsMulti))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.IsSearchable))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.IsFilterable))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.IsExportable))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.IsModerationRelevant))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.IsAnalyticsRelevant))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.IsSystemOwned))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.DefaultTextValue))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.DefaultNumberValue))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.DefaultBooleanValue))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.DefaultDateTimeValue))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.DefaultOptionId))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.DefaultOption))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.MinLength))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.MaxLength))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.RegexPattern))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.MinNumber))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.MaxNumber))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.MinDateTime))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.MaxDateTime))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.AllowedUrlSchemes))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.SourceTemplate))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.SourceTemplateKey))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.SourceTemplateVersion))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.SourceTemplateDefinitionId))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.InstantiatedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.LastSyncedFromTemplateAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.Values))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.CreatedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.CreatedBy))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.IsDeleted))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.DeletedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyDefinition.DeletedBy))]
    [MapProperty("Options.Count", nameof(EventCustomPropertyDefinitionListDto.OptionCount))]
    public static partial EventCustomPropertyDefinitionListDto ToListItem(EventCustomPropertyDefinition source);

    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.EventSession))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.Tenant))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.DefaultOption))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.SourceTemplate))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.Values))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.CreatedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.CreatedBy))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.IsDeleted))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.DeletedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.DeletedBy))]
    public static partial EventSessionCustomPropertyDefinitionDto ToDetail(EventSessionCustomPropertyDefinition source);

    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.EventSession))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.TenantId))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.Tenant))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.Description))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.IsMulti))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.IsSearchable))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.IsFilterable))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.IsExportable))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.IsModerationRelevant))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.IsAnalyticsRelevant))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.IsSystemOwned))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.DefaultTextValue))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.DefaultNumberValue))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.DefaultBooleanValue))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.DefaultDateTimeValue))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.DefaultOptionId))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.DefaultOption))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.MinLength))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.MaxLength))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.RegexPattern))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.MinNumber))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.MaxNumber))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.MinDateTime))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.MaxDateTime))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.AllowedUrlSchemes))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.SourceTemplate))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.SourceTemplateKey))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.SourceTemplateVersion))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.SourceTemplateDefinitionId))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.InstantiatedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.LastSyncedFromTemplateAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.Values))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.CreatedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.CreatedBy))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.IsDeleted))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.DeletedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyDefinition.DeletedBy))]
    [MapProperty("Options.Count", nameof(EventSessionCustomPropertyDefinitionListDto.OptionCount))]
    public static partial EventSessionCustomPropertyDefinitionListDto ToListItem(EventSessionCustomPropertyDefinition source);

    // Templates deliberately retain their existing audit scalar wire contract.
    [MapperIgnoreSource(nameof(EventTemplate.Tenant))]
    [MapperIgnoreSource(nameof(EventTemplate.EventType))]
    [MapperIgnoreSource(nameof(EventTemplate.IsDeleted))]
    [MapperIgnoreSource(nameof(EventTemplate.DeletedAt))]
    [MapperIgnoreSource(nameof(EventTemplate.DeletedBy))]
    [MapProperty(nameof(EventTemplate.CreatedBy), nameof(EventTemplateDto.CreatedBy), Use = nameof(AuditIdentity))]
    [MapProperty(nameof(EventTemplate.UpdatedBy), nameof(EventTemplateDto.UpdatedBy), Use = nameof(AuditIdentity))]
    public static partial EventTemplateDto ToDetail(EventTemplate source);

    [MapperIgnoreSource(nameof(EventTemplate.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(EventTemplate.Tenant))]
    [MapperIgnoreSource(nameof(EventTemplate.EventType))]
    [MapperIgnoreSource(nameof(EventTemplate.CreatedAt))]
    [MapperIgnoreSource(nameof(EventTemplate.CreatedBy))]
    [MapperIgnoreSource(nameof(EventTemplate.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventTemplate.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventTemplate.IsDeleted))]
    [MapperIgnoreSource(nameof(EventTemplate.DeletedAt))]
    [MapperIgnoreSource(nameof(EventTemplate.DeletedBy))]
    [MapProperty("Definitions.Count", nameof(EventTemplateListDto.DefinitionCount))]
    public static partial EventTemplateListDto ToListItem(EventTemplate source);

    [MapperIgnoreSource(nameof(EventSessionTemplate.Tenant))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.EventTemplate))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.IsDeleted))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.DeletedAt))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.DeletedBy))]
    [MapProperty(nameof(EventSessionTemplate.CreatedBy), nameof(EventSessionTemplateDto.CreatedBy), Use = nameof(AuditIdentity))]
    [MapProperty(nameof(EventSessionTemplate.UpdatedBy), nameof(EventSessionTemplateDto.UpdatedBy), Use = nameof(AuditIdentity))]
    public static partial EventSessionTemplateDto ToDetail(EventSessionTemplate source);

    [MapperIgnoreSource(nameof(EventSessionTemplate.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.Tenant))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.EventTemplate))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.CreatedAt))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.CreatedBy))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.IsDeleted))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.DeletedAt))]
    [MapperIgnoreSource(nameof(EventSessionTemplate.DeletedBy))]
    [MapProperty("Definitions.Count", nameof(EventSessionTemplateListDto.DefinitionCount))]
    public static partial EventSessionTemplateListDto ToListItem(EventSessionTemplate source);

    private static string? AuditIdentity(Guid? identity) => identity?.ToString();

    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyDefinition.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyDefinition.EventTemplate))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyDefinition.TenantId))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyDefinition.Tenant))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyDefinition.DefaultOption))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyDefinition.CreatedAt))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyDefinition.CreatedBy))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyDefinition.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyDefinition.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyDefinition.IsDeleted))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyDefinition.DeletedAt))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyDefinition.DeletedBy))]
    private static partial EventTemplateDefinitionDto ToDefinition(EventTemplateCustomPropertyDefinition source);

    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyDefinition.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyDefinition.EventSessionTemplate))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyDefinition.TenantId))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyDefinition.Tenant))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyDefinition.DefaultOption))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyDefinition.CreatedAt))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyDefinition.CreatedBy))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyDefinition.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyDefinition.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyDefinition.IsDeleted))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyDefinition.DeletedAt))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyDefinition.DeletedBy))]
    private static partial EventSessionTemplateDefinitionDto ToDefinition(EventSessionTemplateCustomPropertyDefinition source);

    // Options are flat snapshots: never follow parent, child or definition back-references.
    [MapperIgnoreSource(nameof(CustomPropertyOption.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(CustomPropertyOption.CustomPropertyDefinitionId))]
    [MapperIgnoreSource(nameof(CustomPropertyOption.Definition))]
    [MapperIgnoreSource(nameof(CustomPropertyOption.ParentOptionId))]
    [MapperIgnoreSource(nameof(CustomPropertyOption.ParentOption))]
    [MapperIgnoreSource(nameof(CustomPropertyOption.ChildOptions))]
    [MapperIgnoreSource(nameof(CustomPropertyOption.CreatedAt))]
    [MapperIgnoreSource(nameof(CustomPropertyOption.CreatedBy))]
    [MapperIgnoreSource(nameof(CustomPropertyOption.UpdatedAt))]
    [MapperIgnoreSource(nameof(CustomPropertyOption.UpdatedBy))]
    [MapperIgnoreSource(nameof(CustomPropertyOption.IsDeleted))]
    [MapperIgnoreSource(nameof(CustomPropertyOption.DeletedAt))]
    [MapperIgnoreSource(nameof(CustomPropertyOption.DeletedBy))]
    private static partial CustomPropertyOptionDto ToOption(CustomPropertyOption source);

    [MapperIgnoreSource(nameof(EventCustomPropertyOption.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.EventCustomPropertyDefinitionId))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.Definition))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.ParentOptionId))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.ParentOption))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.ChildOptions))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.SourceTemplateVersion))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.CreatedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.CreatedBy))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.IsDeleted))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.DeletedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyOption.DeletedBy))]
    private static partial EventCustomPropertyOptionDto ToOption(EventCustomPropertyOption source);

    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.EventSessionCustomPropertyDefinitionId))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.Definition))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.ParentOptionId))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.ParentOption))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.ChildOptions))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.SourceTemplateVersion))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.CreatedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.CreatedBy))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.IsDeleted))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.DeletedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyOption.DeletedBy))]
    private static partial EventSessionCustomPropertyOptionDto ToOption(EventSessionCustomPropertyOption source);

    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.EventTemplateCustomPropertyDefinitionId))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.Definition))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.ParentOptionId))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.ParentOption))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.ChildOptions))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.CreatedAt))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.CreatedBy))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.IsDeleted))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.DeletedAt))]
    [MapperIgnoreSource(nameof(EventTemplateCustomPropertyOption.DeletedBy))]
    private static partial EventTemplateOptionDto ToOption(EventTemplateCustomPropertyOption source);

    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.EventSessionTemplateCustomPropertyDefinitionId))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.Definition))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.ParentOptionId))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.ParentOption))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.ChildOptions))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.CreatedAt))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.CreatedBy))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.IsDeleted))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.DeletedAt))]
    [MapperIgnoreSource(nameof(EventSessionTemplateCustomPropertyOption.DeletedBy))]
    private static partial EventSessionTemplateOptionDto ToOption(EventSessionTemplateCustomPropertyOption source);

    [MapperIgnoreSource(nameof(EventCustomPropertyValue.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(EventCustomPropertyValue.Definition))]
    [MapperIgnoreSource(nameof(EventCustomPropertyValue.Event))]
    [MapperIgnoreSource(nameof(EventCustomPropertyValue.TenantId))]
    [MapperIgnoreSource(nameof(EventCustomPropertyValue.Tenant))]
    [MapperIgnoreSource(nameof(EventCustomPropertyValue.Option))]
    [MapperIgnoreSource(nameof(EventCustomPropertyValue.CreatedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyValue.CreatedBy))]
    [MapperIgnoreSource(nameof(EventCustomPropertyValue.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyValue.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventCustomPropertyValue.IsDeleted))]
    [MapperIgnoreSource(nameof(EventCustomPropertyValue.DeletedAt))]
    [MapperIgnoreSource(nameof(EventCustomPropertyValue.DeletedBy))]
    public static partial EventCustomPropertyValueDto ToValue(EventCustomPropertyValue source);

    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.ConcurrencyStamp))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.Definition))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.EventSession))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.TenantId))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.Tenant))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.Option))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.CreatedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.CreatedBy))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.UpdatedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.UpdatedBy))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.IsDeleted))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.DeletedAt))]
    [MapperIgnoreSource(nameof(EventSessionCustomPropertyValue.DeletedBy))]
    public static partial EventSessionCustomPropertyValueDto ToValue(EventSessionCustomPropertyValue source);
}
