using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace ISLAMU.Event.SetupAssistant.Cli;

public sealed record SetupCliRegisteredOperationMetadata(
    string Name,
    IReadOnlyList<string> Options);

public sealed record SetupCliRegisteredCommandMetadata(
    string Name,
    IReadOnlyList<SetupCliRegisteredOperationMetadata> Operations,
    IReadOnlyList<string> Options);

public static class SetupCliCommandSchemaMetadata
{
    public const string RelativePath = "schemas/event-setup-command-v1.schema.json";
    public static IReadOnlyList<SetupCliRegisteredCommandMetadata> Commands { get; } =
        SetupCliCommandRegistry.Families.Select(family => new SetupCliRegisteredCommandMetadata(
                family.Name,
                family.Operations.Select(operation => new SetupCliRegisteredOperationMetadata(
                    operation.Name,
                    operation.Options.Select(option => option.Name)
                        .Append("--help")
                        .Distinct(StringComparer.Ordinal)
                        .Order(StringComparer.Ordinal)
                        .ToArray())).ToArray(),
                family.Operations.SelectMany(operation => operation.Options.Select(option => option.Name))
                    .Append("--help")
                    .Distinct(StringComparer.Ordinal)
                    .Order(StringComparer.Ordinal)
                    .ToArray()))
            .ToArray();
    public static IReadOnlyList<string> Families { get; } =
        Commands.Select(command => command.Name).ToArray();
    public static IReadOnlyList<string> Operations { get; } =
        Commands.SelectMany(command => command.Operations.Select(operation => operation.Name))
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToArray();
    public static IReadOnlyList<string> Options { get; } =
        Commands.SelectMany(command => command.Options)
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToArray();

    public static byte[] GenerateSchema()
    {
        JsonObject definitions = new()
        {
            ["invocation"] = ObjectSchema(["commandFamily", "operation", "mode"], new()
            {
                ["commandFamily"] = Enum(Families),
                ["operation"] = Enum(Operations),
                ["mode"] = Enum(["machine"])
            }),
            ["diagnostic"] = ObjectSchema(["code", "path", "severity"], new()
            {
                ["code"] = String(1, 96, "^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$"),
                ["path"] = String(1, 256, "^\\$(?:\\.[a-z][A-Za-z0-9-]*)*$"),
                ["severity"] = Enum(["info", "warning", "error"])
            }),
            ["artifact"] = ObjectSchema(["kind", "mediaType", "digest", "sensitivity", "coverage", "readiness", "pathIntent", "writeStatus"], new()
            {
                ["kind"] = Enum(["catalogue", "configuration-manifest", "tenant-configuration-package", "dotenv-template", "legal-draft", "doctor-report", "operator-identity-manifest", "operator-identity-import-request"]),
                ["mediaType"] = String(1, 128, "^[a-z0-9][a-z0-9.+-]*/[a-z0-9][a-z0-9.+-]*(?:;v=[a-z0-9.-]+)?$"),
                ["digest"] = String(null, null, "^[0-9a-f]{64}$"),
                ["sensitivity"] = Enum(["public", "sensitive"]),
                ["coverage"] = Ref("coverage"),
                ["readiness"] = Ref("readiness"),
                ["pathIntent"] = Enum(["none", "input", "output", "stdout"]),
                ["writeStatus"] = Enum(["none", "planned", "written"])
            }),
            ["coverage"] = ObjectSchema(["coveredKeys", "missingKeys"], new()
            { ["coveredKeys"] = Ref("keyList"), ["missingKeys"] = Ref("keyList") }),
            ["readiness"] = ObjectSchema(["state", "missingKeys", "blockedKeys"], new()
            { ["state"] = Enum(["ready", "incomplete", "blocked"]), ["missingKeys"] = Ref("keyList"), ["blockedKeys"] = Ref("keyList") }),
            ["keyList"] = new JsonObject
            {
                ["type"] = "array",
                ["maxItems"] = 256,
                ["items"] = String(1, 128, "^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$")
            }
        };
        JsonObject root = new()
        {
            ["_metadata"] = new JsonObject
            {
                ["about"] = Array(["ABOUT" + "ME: Defines the closed value-safe machine response contract for event-setup commands.",
                    "ABOUT" + "ME: Generated by the package-free SetupCliCommandSchemaGenerator; edit compiled CLI metadata."]),
                ["generatedBy"] = "ISLAMU.Event.SetupAssistant.Cli.CommandSchemaGenerator",
                ["commandOptions"] = Array(Options),
                ["repeatableOptions"] = Array(["--capability", "--provider"]),
                ["commands"] = new JsonArray(Commands.Select(command => (JsonNode?)new JsonObject
                {
                    ["name"] = command.Name,
                    ["operations"] = new JsonArray(command.Operations.Select(operation => (JsonNode?)new JsonObject
                    {
                        ["name"] = operation.Name,
                        ["options"] = Array(operation.Options)
                    }).ToArray()),
                    ["options"] = Array(command.Options)
                }).ToArray())
            },
            ["$schema"] = "https://json-schema.org/draft/2020-12/schema",
            ["$id"] = "https://schemas.islamu.org/event/setup-command/v1/schema.json",
            ["type"] = "object",
            ["additionalProperties"] = false,
            ["required"] = Array(["schemaVersion", "invocation", "status", "exitCategory", "exitCode", "dryRun", "diagnostics", "artifacts", "coverage", "readiness"]),
            ["properties"] = new JsonObject
            {
                ["schemaVersion"] = new JsonObject { ["const"] = "event-setup-command/v1" },
                ["invocation"] = Ref("invocation"),
                ["status"] = ExitNames(),
                ["exitCategory"] = ExitNames(),
                ["exitCode"] = new JsonObject { ["enum"] = new JsonArray(System.Enum.GetValues<SetupCliExitCode>().Select(value => (JsonNode?)JsonValue.Create((int)value)).ToArray()) },
                ["dryRun"] = new JsonObject { ["type"] = "boolean" },
                ["diagnostics"] = BoundedArray("diagnostic", 128),
                ["artifacts"] = BoundedArray("artifact", 32),
                ["coverage"] = Ref("coverage"),
                ["readiness"] = Ref("readiness")
            },
            ["$defs"] = definitions
        };
        string json = root.ToJsonString(new JsonSerializerOptions { WriteIndented = true }).Replace("\r\n", "\n", StringComparison.Ordinal) + "\n";
        return Encoding.UTF8.GetBytes(json);
    }

    private static JsonObject ObjectSchema(IEnumerable<string> required, JsonObject properties) => new()
    { ["type"] = "object", ["additionalProperties"] = false, ["required"] = Array(required), ["properties"] = properties };
    private static JsonObject String(int? minimum, int? maximum, string pattern)
    {
        JsonObject result = new() { ["type"] = "string" };
        if (minimum.HasValue) result["minLength"] = minimum.Value;
        if (maximum.HasValue) result["maxLength"] = maximum.Value;
        result["pattern"] = pattern; return result;
    }
    private static JsonObject Enum(IEnumerable<string> values) => new() { ["enum"] = Array(values) };
    private static JsonObject ExitNames() => Enum(System.Enum.GetValues<SetupCliExitCode>().Select(value => value.ToString().ToLowerInvariant()));
    private static JsonObject Ref(string name) => new() { ["$ref"] = "#/$defs/" + name };
    private static JsonObject BoundedArray(string item, int maximum) => new()
    { ["type"] = "array", ["maxItems"] = maximum, ["items"] = Ref(item) };
    private static JsonArray Array(IEnumerable<string> values) => new(values.Select(value => (JsonNode?)JsonValue.Create(value)).ToArray());
}
