// <auto-generated />
using System;
using Explore.Persistence.Privacy.ErasureAuthority;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Explore.Persistence.Migrations.PrivacyErasureAuthority
{
    [DbContext(typeof(PrivacyErasureAuthorityDbContext))]
    [Migration("20261002045117_RetainedExternalIdentityFences")]
    partial class RetainedExternalIdentityFences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("privacy_erasure_authority")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Explore.Domain.PrivacyErasureCounter", b =>
                {
                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasColumnName("singleton");

                    b.Property<string>("IdentityKeyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identity_key_id");

                    b.Property<string>("IdentityKeyVerificationTag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identity_key_verification_tag");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.Property<long>("RetainedFloorSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("retained_floor_sequence");

                    b.HasKey("Singleton")
                        .HasName("pk_authority_counter");

                    b.ToTable("authority_counter", "privacy_erasure_authority", t =>
                        {
                            t.HasCheckConstraint("ck_privacy_erasure_authority_counter_nonnegative", "last_sequence >= 0");

                            t.HasCheckConstraint("ck_privacy_erasure_authority_counter_retained_floor", "retained_floor_sequence >= 0 AND retained_floor_sequence <= last_sequence");

                            t.HasCheckConstraint("ck_privacy_erasure_authority_counter_singleton", "singleton");
                        });
                });

            modelBuilder.Entity("Explore.Domain.PrivacyErasureIdentityFence", b =>
                {
                    b.Property<long>("AuthoritySequence")
                        .HasColumnType("bigint")
                        .HasColumnName("authority_sequence");

                    b.Property<int>("IdentityKind")
                        .HasColumnType("integer")
                        .HasColumnName("identity_kind");

                    b.Property<string>("KeyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_id");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<DateTime>("RetentionExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_expires_at_utc");

                    b.HasKey("AuthoritySequence", "IdentityKind", "KeyId", "Fingerprint")
                        .HasName("pk_identity_fences");

                    b.HasIndex("IdentityKind", "KeyId", "Fingerprint")
                        .HasDatabaseName("ix_identity_fences_identity_kind_key_id_fingerprint");

                    b.ToTable("identity_fences", "privacy_erasure_authority", t =>
                        {
                            t.HasCheckConstraint("ck_identity_fences_digest", "length(fingerprint) = 64");

                            t.HasCheckConstraint("ck_identity_fences_key", "length(key_id) BETWEEN 1 AND 64");

                            t.HasCheckConstraint("ck_identity_fences_kind", "identity_kind BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Explore.Domain.PrivacyErasureIntent", b =>
                {
                    b.Property<long>("AuthoritySequence")
                        .HasColumnType("bigint")
                        .HasColumnName("authority_sequence");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_id");

                    b.Property<bool>("IsLegalHoldPseudonymized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_legal_hold_pseudonymized");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("policy_version");

                    b.Property<short>("ReasonCode")
                        .HasColumnType("smallint")
                        .HasColumnName("reason_code");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<DateTime>("RetentionExpiresAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_expires_at_utc")
                        .HasDefaultValueSql("'infinity'::timestamp with time zone");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<short>("SubjectKind")
                        .HasColumnType("smallint")
                        .HasColumnName("subject_kind");

                    b.HasKey("AuthoritySequence")
                        .HasName("pk_erasure_intents");

                    b.HasIndex("SubjectKind", "SubjectId")
                        .HasDatabaseName("ix_erasure_intents_subject_kind_subject_id");

                    b.HasIndex("IntentId", "SubjectKind", "PolicyVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_erasure_intents_intent_id_subject_kind_policy_version");

                    b.ToTable("erasure_intents", "privacy_erasure_authority", t =>
                        {
                            t.HasCheckConstraint("ck_privacy_erasure_intents_intent_rfc4122_variant", "substring(intent_id::text, 20, 1) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_intent_uuid_v7", "is_legal_hold_pseudonymized OR substring(intent_id::text, 15, 1) = '7'");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_policy_version", "policy_version > 0");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_reason", "reason_code BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_retention", "retention_expires_at_utc > recorded_at_utc");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_sequence", "authority_sequence > 0");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_server_time_order", "recorded_at_utc >= requested_at_utc");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_subject_kind", "subject_kind = 1");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_subject_nonempty", "subject_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Explore.Domain.PrivacyErasureIdentityFence", b =>
                {
                    b.HasOne("Explore.Domain.PrivacyErasureIntent", null)
                        .WithMany("IdentityFences")
                        .HasForeignKey("AuthoritySequence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_fences_erasure_intents_authority_sequence");
                });

            modelBuilder.Entity("Explore.Domain.PrivacyErasureIntent", b =>
                {
                    b.Navigation("IdentityFences");
                });
#pragma warning restore 612, 618
        }
    }
}
